name: Build and push Docker image

on:
  push:
    branches:
      - main
      - feat/docker_build

env:
  IMAGE_NAME: ghcr.io/ritika-14/newimage

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: $IMAGE_NAME
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHRC_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHRC_TOKEN}}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME .
      
      - name: Run tests on Docker Image
        uses: docker://$IMAGE_NAME:latest
        with:
          entrypoint: /bin/sh
          args: -c "pytest"

      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push $IMAGE_NAME