name: Docker Build, Test, and Publish
on:
  push:
    branches:
      - main
      - feat/kubernetes
      
jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/ritika-14/newimage1
        tag-sha: false
        tag-edge: false
        tag-latest: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GHCR_TOKEN}}

    - name: Build and test Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: ${{steps.docker_meta.outputs.tags}}
        file: ./Dockerfile

    - name: Setup Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: python -m pip install -U -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=src
        pytest

    - name: Publish Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{steps.docker_meta.outputs.tags}}
        file: ./Dockerfile
        
